library:
  join: backbone-modelref.js
  compress: true
  directories: [src]

tests:
  output: ./build
  directories:
    - test/backbone-modelref_core
    - test/packaging
  options:
    test:
      command: phantomjs
      runner: phantomjs-qunit-runner.js
    build:
      no_files_ok: ['test/packaging']

postinstall:
  copy_latest_underscore:
    command: 'cp'
    args: ['node_modules/underscore/underscore.js', 'vendor/underscore-latest.js']
  copy_latest_backbone:
    command: 'cp'
    args: ['node_modules/backbone/backbone.js', 'vendor/backbone-latest.js']
