library:
  join: backbone-modelref.js
  compress: true
  files:
    - src/**/*.coffee

tests:
  output: build
  directories:
    - test/core
    - test/packaging
  files:
    - '**/*.coffee'
  modes:
    build:
      bundles:
        test/packaging/build/bundle-latest.js:
          underscore: underscore
          backbone: backbone
          backbone-modelref: backbone-modelref.js
        test/packaging/build/bundle-legacy.js:
          underscore: vendor/underscore-1.0.3.js
          backbone: vendor/backbone-0.5.1.js
          backbone-modelref: backbone-modelref.js
      no_files_ok: ['test/packaging']
    test:
      command: phantomjs
      runner: phantomjs-qunit-runner.js
      files:
        - '**/*.html'

postinstall:
  commands:
    - 'cp underscore vendor/underscore-latest.js'
    - 'cp backbone vendor/backbone-latest.js'