library:
  join: backbone-modelref.js
  compress: true
  files:
    - src/**/*.coffee

tests:
  output: build
  directories:
    - test/core
    - test/packaging
  files:
    - '**/*.coffee'
  options:
    test:
      command: phantomjs
      runner: phantomjs-qunit-runner.js
      files:
        - '**/*.html'
    build:
      no_files_ok: ['test/packaging']

postinstall:
  copy_latest_underscore:
    command: 'cp'
    args: ['underscore', 'vendor/underscore-latest.js']
  copy_latest_backbone:
    command: 'cp'
    args: ['backbone', 'vendor/backbone-latest.js']
